version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: serde
    versions:
    - 1.0.123
    - 1.0.124
  - dependency-name: serde_json
    versions:
    - 1.0.61
    - 1.0.62
    - 1.0.63
  - dependency-name: futures
    versions:
    - 0.3.12
    - 0.3.13
  - dependency-name: hyper
    versions:
    - 0.14.2
    - 0.14.4
  - dependency-name: http
    versions:
    - 0.2.3
  - dependency-name: tokio
    versions:
    - 0.2.24
  - dependency-name: warp
    versions:
    - 0.2.5
